-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Buses"
(
    id_bus serial NOT NULL,
    capacidad numeric,
    PRIMARY KEY (id_bus)
);

CREATE TABLE IF NOT EXISTS public.rutas
(
    id_rutas serial NOT NULL,
    id_buses integer,
    id_conductores integer,
    id_paradas integer,
    PRIMARY KEY (id_rutas)
);

CREATE TABLE IF NOT EXISTS public."Paradas"
(
    id_paradas serial NOT NULL,
    paradas character varying,
    PRIMARY KEY (id_paradas)
);

CREATE TABLE IF NOT EXISTS public."Conductor"
(
    id_conductor serial NOT NULL,
    "Nombre" character varying,
    PRIMARY KEY (id_conductor)
);

ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT id_conductores FOREIGN KEY (id_conductores)
    REFERENCES public."Conductor" (id_conductor) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT id_paradas FOREIGN KEY (id_paradas)
    REFERENCES public."Paradas" (id_paradas) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.rutas
    ADD CONSTRAINT id_buses FOREIGN KEY (id_buses)
    REFERENCES public."Buses" (id_bus) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;