-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Libros"
(
    id_libro serial NOT NULL,
    id_temas integer,
    titulo character,
    autor character,
    "nº_ejemplares" integer,
    PRIMARY KEY (id_libro)
);

CREATE TABLE IF NOT EXISTS public."Temas"
(
    id_tema serial NOT NULL,
    "Nombre_tema" character,
    PRIMARY KEY (id_tema)
);

CREATE TABLE IF NOT EXISTS public."Reserva"
(
    id_reserva serial NOT NULL,
    id_libro integer,
    id_socios integer,
    "Fecha_inicio" date,
    "Fecha_final" date,
    PRIMARY KEY (id_reserva)
);

CREATE TABLE IF NOT EXISTS public."Socio"
(
    id_socio serial NOT NULL,
    PRIMARY KEY (id_socio)
);

ALTER TABLE IF EXISTS public."Libros"
    ADD CONSTRAINT id_temas FOREIGN KEY (id_temas)
    REFERENCES public."Temas" (id_tema) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reserva"
    ADD CONSTRAINT id_libro FOREIGN KEY (id_libro)
    REFERENCES public."Libros" (id_libro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Reserva"
    ADD CONSTRAINT id_socio FOREIGN KEY (id_socios)
    REFERENCES public."Socio" (id_socio) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;